### ISSUE TITLE
Unknown identifier: mi

### ISSUE THREAD

**Issue by hallzy** [sharkdp/insect#242] opened 2020-10-14 05:18 UTC
I noticed something I would consider to be weird with some of the units:

```
>>> 10 miles

  10 mi

   = 10 mi
```

Note that insect returns the units as `mi`, but if I input units as `mi`:

```
>>> 10 mi

  10 × mi

  Unknown identifier: mi
```

it is not able to interpret it. I don't know if there are other units that do this as well.

Is there a reason for this that I have missed, or was this intentional?

**Comment by sharkdp** [comment] 2020-10-17 17:16
Thank you for reporting this. This is a duplicate of #151. Hasn't been fixed yet, unfortunately.

**Closed** 2020-10-17 17:17 UTC
Labels: duplicate
