### ISSUE TITLE
Date manipulations

### ISSUE THREAD

**Issue by 183amir** [sharkdp/insect#128] opened 2017-09-20 15:26 UTC
Hi,

I was wondering if you could add dates manipulation to the program as well.
Something like:
```
07.01.2018 - 22.11.2017
22 Jan + 2
```

**Comment by sharkdp** [comment] 2017-09-21 19:04
Thank you for the suggestion.

It's not really in focus for Insect, but if there is a really clear path to take - and if it doesn't interfere with any of the existing functionality - I could imagine supporting it.

Unfortunately, at the moment, I don't see a good way in which we could support this. The problem is the following: Everything in Insect is represented as a physical quantity (e.g. `4 hours`, `12 weeks` or `2 kilogram`). This would mean that we would have to interpret a date like `07.01.2018` as a physical quantity, as well. The only reasonable quantity that comes to mind would be the absolute time with respect to some origin (1 Jan, year 0). But this introduces a lot of problems:

* Taking something as simple `7 days + 1 month + 2018 years = 736607 days` is not very helpful because there are leap years, months with different amount of days, changes of calendars, and many more subtleties.
* Even if we account for all of those subtleties and calculate the exact amount of days since 0, we could not use these quantities to perform useful calculations because the reference point would be lost (is `7 days` just a time-delay of one week or the date `08.01.0000`?).

> `22 Jan + 2`

Even if I can guess what you would like to compute with an input like this, I would really like to avoid supporting ambiguous syntax like this.

**Comment by sharkdp** [comment] 2017-10-07 14:33
Closing this for now.

**Closed by sharkdp** 2017-10-07 14:33 UTC

**Comment by EricKolibacz** [comment] 2023-09-22 08:44
[Numi](https://numi.app/) calculator for Mac OS implements partially the suggested functionality (keyword `now` [here](https://github.com/nikolaeu/numi/wiki/Documentation#time-zone-conversion) or date [here](https://github.com/nikolaeu/numi/wiki/Documentation#date--time)). Would be very handy to have this for Insect too. Is there a chance for reconsideration?

**Comment by sharkdp** [comment] 2023-09-26 12:14
There is. If you have a good proposal on how to support this in Insect (or the follow-up project, https://github.com/sharkdp/numbat)
