### ISSUE TITLE
Decimal seperator for USD / EUR / finance numbers

### ISSUE THREAD

**Issue by chinese-soup** [sharkdp/insect#249] opened 2021-02-19 01:19 UTC
Hello.
I couldn't find this specific issue, so hopefully it's not a duplicate.

I'd like to ask if anyone would consider adding a configurable(?) decimal seperator for numbers. This is useful mainly in I guess financial kind of calculations where scientific notation isn't very practical to the human eye. I'm thinking at least either for USD / EUR / custom currency variable / etc. answers or some user configurable setting for all the numbers that would otherwise not end up being delimited.

See:
https://en.wikipedia.org/wiki/Decimal_separator#Examples_of_use

**Example:**
Current behavior:
```
>>> 1000 × 6

  1000 × 6

   = 6000

```

Proposed behavior:
a)
```
>>> decimal_seperator = "'"  # or something along the lines of
>>> 1000 × 6

  1000 × 6

   = 6'000

>>> decimal_seperator = " "
>>> 1000 × 6

  1000 × 6

   = 6 000

```
b) 
```
>>> 1000 × 6 USD

  1000 × 6 USD

   = 6,000 USD # US uses USD, US uses comma , as a delimiter etc.
```

What do you think?

**Comment by sharkdp** [comment] 2021-02-20 10:52
Thank you for your request.

It kind of came up here: #104, #175. 

So far, we have a `.insectrc` startup file, but insect doesn't really have any configuration settings so far. But it's definitely something that could be implemented.

For a long time, I have been planning a full rewrite of `insect`. Having user-settings like this would definitely be something that would be included in a v2. That being said, it should also be possible to include this in the current version. The problem is that almost no one is familiar with PureScript. That's the main reason why I would rewrite the project.

**Comment by mhmdanas** [comment] 2021-06-29 22:24
> That's the main reason why I would rewrite the project.

Rewrite it as in another language? If so, what are some candidates?

**Comment by sharkdp** [comment] 2021-06-30 07:55
There are no serious plans, but I once started a small experiment in Rust, using `nom` to build a parser. I think it would be a good fit because the PureScript version is starting to show some performance problems. Rust would be a good fit because we could still target both the web (WASM) and the terminal.

**Comment by mhmdanas** [comment] 2021-06-30 11:47
> I think it would be a good fit because the PureScript version is starting to show some performance problems. 

I would be interested in taking a stab at fixing those problems. Any examples (maybe a new issue should be made for this)?

**Comment by sharkdp** [comment] 2021-06-30 19:44
There are two things that come to my mind right now:

- The startup time of the terminal version
- The (somewhat ridiculous) long time to run the whole test suite.

**Comment by mhmdanas** [comment] 2022-09-16 14:36
This is only tangentially related (the issue says nothing of separators in _input_, only _output_), but I've been thinking about having a separator like `_` (so you can input e.g. `1_234_567`). `_` was added recently as an alias for `ans` (https://github.com/sharkdp/insect/issues/159), but we should be able to work out a way to disambiguate between the two.

Note that I personally don't really care about having a `_` separator, so I won't be adding it until somebody asks for it.

**Comment by sharkdp** [comment] 2023-09-26 20:22
That follow up project is now here! And we also have a follow-up ticket: https://github.com/sharkdp/numbat/issues/152

**Closed by sharkdp** 2023-09-26 20:22 UTC
