### ISSUE TITLE
Can it use Windows Terminal instead of Windows' default console (cmd.exe)?

### ISSUE THREAD

**Issue by giladrefael** [sharkdp/insect#337] opened 2022-09-15 05:51 UTC
The app opens by default in `cmd.exe` where glyphs aren't supported. Is it possible to make it run in Windows Terminal if available? Attaching an image to show the visual difference between running the app from Windows Explorer (left) vs running from CLI in Windows terminal (right). Both using Fira Code nerd font.

![image](https://user-images.githubusercontent.com/7063482/190324248-1b0f9e19-b4dd-4630-9f8d-561b1b3e1738.png)

**Comment by giladrefael** [comment] 2022-09-15 11:02
A workaround I did is to create a batch file that runs the following command to launch `insect` from Windows terminal
`wt insect.exe`

**Comment by mhmdanas** [comment] 2022-09-15 15:05
I don't have a solution for the issue itself, but please note that we've decided not to ship executables with Insect releases anymore (see https://github.com/sharkdp/insect/issues/297), so the next release will have no executables for you to use. Instead, you'll have to install Insect from npm using `npm install insect`, or use https://insect.sh. If you have any alternatives to nexe, please feel free to suggest them and we'll consider using them.

**Comment by mhmdanas** [comment] 2022-12-20 02:38
No reply to my previous comment, and the issue is obsolete anyway, so closing. Feel free to leave a comment if you have any questions.

**Closed by mhmdanas** 2022-12-20 02:38 UTC
