### ISSUE TITLE
Exponential sign deletes last calculation

### ISSUE THREAD

**Issue by ssummer1337** [sharkdp/insect#149] opened 2018-04-11 13:20 UTC
I don't know if this is intended or not, but I currently have the following problem:

If you write a simple calculation like '1+1' and hit enter it shows the result of '2'.
When now using the 'arrow-up'-key to get the last calculation, the '1+1' shows up again, but I can't use the exponential sign '^' now as it removes the last calculation.

It seems like a buffer problem because it somehow also restores deleted characters as soon as using the exponential sign.

Best regards,

**Comment by sharkdp** [comment] 2018-04-13 19:33
Thank you for your feedback.

I can't reproduce this. Do you use the web version? If so, which browser and operating system do you use?

Also, could you check if the same thing happens in [this jquery.terminal demo](https://terminal.jcubic.pl/#demo)?

**Comment by ssummer1337** [comment] 2018-04-13 19:51
I have tried with Windows 7 (Firefox and Chromium), Windows 10 (Firefox and Chrome[JavaScript V8 6.5.254.41]).

I also tried Edge and it seem to work there.

Regarding your jquery demo. The calculation only gets shifted by one space, but seems "fine".

**Comment by sharkdp** [comment] 2018-04-13 20:30
Thanks.

This is *probably* due to the external dependency jquery.terminal.

Note for whoever might be working on this: It could be that this is fixed by upgrading to the latest version of jquery.terminal. However, it is not straightforward since we have a custom terminal.css file that seems to be out of date.

**Comment by sharkdp** [comment] 2020-01-25 22:17
Should be fixed in the latest online version.

**Closed** 2020-01-25 22:17 UTC
Labels: bug, help-wanted
