### ISSUE TITLE
Ignore 2+ digits after operation sign

### ISSUE THREAD

**Issue by bullbesh** [sharkdp/insect#300] opened 2022-05-24 06:58 UTC
I'm facing the problem that on mobile I can't perform operations on _2+ character_ digits after the sign of the operation.

For example, I cant divide 1940 by 40

![Screenshot_20220524-095017_Chrome.jpg](https://user-images.githubusercontent.com/69913622/169967768-1715805b-dd25-4f47-95c4-f19e12947c91.jpg)

It's divide 1940 by 4 instead.

If I can't find something important in the documentation, tell me about it 🤠

**Comment by mhmdanas** [comment] 2022-05-24 12:21
I'm having a hard time understanding what the bug is; you're dividing 1910 by 4 in the screenshot with a correct result, but you mention dividing 1940 by 4 instead. Both work properly on Insect on my phone. Can you clarify the issue?

**Comment by sharkdp** [comment] 2022-05-24 16:55
I can't reproduce this either because the keyboard doesn't even open on my phone. But I can very well imagine that there is a bug, because I never tested the website on mobile.

I understood the original bug as: *try* to type "1940 / 40" => the "0" will not even be displayed, so "1940 / 4" is being computed.

Maybe related: #286 

I would really appreciate if someone with more web development skills as me would take a look at this. But I am assuming it's an upstream bug in the JS terminal library that we are using.

**Comment by bullbesh** [comment] 2022-05-24 17:18
> What browsers and operating systems are each of you using @sharkdp @bullbesh?

Google Chrome, Android 11

**Comment by bullbesh** [comment] 2022-05-25 13:37
I just now saw that I was dividing 1910 instead of 1940. The meaning of the issue was that it was not possible to add "0" to the number "40". My bad 😞

**Comment by mhmdanas** [comment] 2022-06-23 21:38
Well, great, now the keyboard doesn't open for me either, using Mull (a Firefox fork) on Android 12. I'll have to investigate this.

**Comment by apandada1** [comment] 2023-07-26 18:41
I cannot reproduce this in Android 11/Firefox/Gboard.
Tapping twice opens the keyboard, and I can write `40` after the `/`.

Also, in case you are experiencing issues with the web version of insect with Android, you can use the Terminal version for Android instead https://github.com/sharkdp/insect#terminal-version

**Comment by sharkdp** [comment] 2023-09-26 20:31
For the follow up project, https://numbat.dev/, we have a much better mobile version. It works fine for me on Firefox mobile. @bullbesh Does this error still appear for you on https://numbat.dev/?

I'm tentatively closing this.

**Closed by sharkdp** 2023-09-26 20:31 UTC
Labels: bug
