### ISSUE TITLE
moving the cursor on a long line does surprising things

### ISSUE THREAD

**Issue by Pomax** [sharkdp/insect#83] opened 2017-06-24 16:22 UTC
move the cursor around in a long line actually causes lines the get wrapped at the cursor, which does... really funky things =)

In the following gif all I'm doing is hitting "left" to move the cursor one spot to the left in my expression:

![cursor](https://user-images.githubusercontent.com/177243/27510077-9c307d38-58be-11e7-9a6f-0ca283ffd99a.gif)

**Comment by sharkdp** [comment] 2017-06-24 16:40
Yes, thanks. This is a duplicate of #78

**Closed by sharkdp** 2017-06-24 16:40 UTC
